name: Build and Push Docker Image

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:$TIMESTAMP .  # Tag with timestamp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest .  # Also tag as 'latest'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:$TIMESTAMP  # Push timestamp tag
          docker push ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest  # Push latest tag
